SELECT DANHBO FROM TB_DULIEUKHACHHANG WHERE MADMA='TH-06-03' AND KY_<=8 AND NAM<=2013
AND DANHBO NOT IN (SELECT DANHBO FROM DMA_TEST)
ORDER BY  LOTRINH ASC



DELETE FROM DMA_TEST 

UPDATE DMA_TEST SET DANHBO= REPLACE(DANHBO,' ' ,'')

SELECT MADMA,COUNT(*)
FROM DMA_TEST
GROUP BY MADMA

SELECT DANHBO FROM DMA_TEST GROUP BY DANHBO HAVING COUNT(DANHBO) >1


SELECT * FROM DMA_TEST
WHERE DANHBO IN (SELECT DANHBO FROM DMA_TEST GROUP BY DANHBO HAVING COUNT(DANHBO) >1)
ORDER BY DANHBO ASC


-----------------------
SELECT DANHBO,HOTEN, SONHA + ' ' + TENDUONG,MADMA, KY_,NAM
FROM TB_DULIEUKHACHHANG
WHERE   DANHBO  IN (SELECT DANHBO FROM DMA_TEST  ) 
ORDER BY MADMA ASC


SELECT *
FROM TB_DULIEUKHACHHANG_HUYDB
WHERE  DANHBO  IN (SELECT DANHBO FROM DMA_TEST )
AND  DANHBO NOT  IN (SELECT DANHBO FROM TB_DULIEUKHACHHANG )
ORDER BY MADMA ASC

SELECT *
FROM DMA_TEST 
WHERE  DANHBO  NOT IN (SELECT DANHBO FROM TB_DULIEUKHACHHANG ) 


-------------------

DELETE FROM TB_DULIEUKHACHHANG_HUYDB WHERE MADMA='TH-06-03'

SELECT * FROM DMA_TEST WHERE MADMA='TH-04-02' AND DANHBO NOT IN (SELECT DANHBO FROM TB_DULIEUKHACHHANG WHERE MADMA='TH-04-02')

SELECT DANHBO FROM DMA_TEST WHERE DANHBO NOT IN ( SELECT DANHBO FROM TB_DULIEUKHACHHANG WHERE  MADMA='TH-04-02')

SELECT DANHBO FROM DMA_TEST WHERE REPLACE(DANHBO,' ','')='13152188483'

UPDATE TB_DULIEUKHACHHANG SET MADMA='TH-04-02' WHERE  DANHBO IN (SELECT DANHBO FROM DMA_TEST )

---
UPDATE TB_DULIEUKHACHHANG SET MADMA= NULL WHERE MADMA='TH-06-03' AND KY_<=8 AND NAM<=2013
UPDATE TB_DULIEUKHACHHANG SET MADMA='TH-06-03' WHERE DANHBO IN (SELECT DANHBO FROM DMA_TEST)

 
UPDATE TB_DULIEUKHACHHANG SET MADMA='TH-06-03' WHERE  DANHBO   IN (SELECT DANHBO FROM DMA_TEST WHERE MADMA='TH-06-02')


SELECT *
FROM DMA_TEST 
WHERE  DANHBO  NOT IN (SELECT DANHBO FROM TB_DULIEUKHACHHANG ) 


SELECT DANHBO,HOTEN, SONHA + ' ' + TENDUONG,MADMA, KY_,NAM
FROM TB_DULIEUKHACHHANG
WHERE MADMA='TH-06-02' and   DANHBO IN (SELECT DANHBO FROM DMA_TEST )
ORDER BY KY_ DESC, NAM ASC



SELECT DANHBO,HOTEN, SONHA + ' ' + TENDUONG,MADMA, CONVERT(VARCHAR(10),KY)+'/'+CONVERT(VARCHAR(10),NAM)
FROM TB_DULIEUKHACHHANG
WHERE MADMA = 'TH-01-02'  AND KY_=5 
ORDER BY MADMA ASC

AND NAM <=2013 and   DANHBO NOT  IN (SELECT DANHBO FROM DMA_TEST WHERE MADMA='TH-01-02')


SELECT DANHBO,HOTEN, SONHA + ' ' + TENDUONG,MADMA, CONVERT(VARCHAR(10),KY)+'/'+CONVERT(VARCHAR(10),NAM)
FROM TB_DULIEUKHACHHANG 
WHERE MADMA = 'TH-01-02' AND KY_<6 AND NAM <=2013


SELECT DANHBO,HOTEN, SONHA + ' ' + TENDUONG,MADMA, CONVERT(VARCHAR(10),KY)+'/'+CONVERT(VARCHAR(10),NAM)
FROM TB_DULIEUKHACHHANG 
WHERE    DANHBO  IN (SELECT DANHBO FROM DMA_TEST )
ORDER BY MADMA ASC


SELECT * FROM  TB_DULIEUKHACHHANG
WHERE MADMA= 'TH-04-02' and KY_<=6 AND NAM<=2013

SELECT DANHBO,COUNT(*) FROM DMA_TEST
GROUP BY DANHBO 
HAVING COUNT(*)>1

SELECT DANHBO
FROM TB_DULIEUKHACHHANG_HUYDB
WHERE    DANHBO  IN (SELECT DANHBO FROM DMA_TEST)

 

SELECT DANHBO,SONHA +' ' + TENDUONG , MADMA,CONVERT(VARCHAR(10),KY)+'/'+CONVERT(VARCHAR(10),NAM)
FROM TB_DULIEUKHACHHANG  
WHERE    DANHBO  IN (SELECT DANHBO FROM DMA_TEST)
ORDER BY   NAM ASC, KY ASC , MADMA DESC


DELETE FROM TB_DULIEUKHACHHANG_HUYDB WHERE DANHBO='13141980558'





SELECT DMA_TEST.DANHBO,HOTEN, SONHA + ' ' + TENDUONG,DMA_TEST.MADMA  FROM DMA_TEST 
LEFT JOIN TB_DULIEUKHACHHANG
ON TB_DULIEUKHACHHANG.DANHBO = DMA_TEST.DANHBO
WHERE DMA_TEST.DANHBO IN ('13162270154','13162270155','13162270161','13162276222','13172412412','13172412420','13172412423','13172412444','13172412445','13172426795')
ORDER BY DMA_TEST.DANHBO ASC

SELECT DANHBO,MADMA, COUNT(DANHBO)
FROM DMA_TEST 
GROUP BY DANHBO,MADMA
HAVING COUNT(DANHBO) >1


AND  DANHBO NOT IN (SELECT DANHBO FROM DMA_TEST WHERE MADMA='TH-08-11')