UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI
		AND TB_DULIEUKHACHHANG.DOT IN ('04')

------
UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI
FROM dbo.HdTH03
WHERE TB_DULIEUKHACHHANG.DANHBO = dbo.HdTH03.DANHBO

SELECT * 
FROM DocSo_PHT.dbo.DS2012
WHERE CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI