UPDATE KHACHHANG
SET KHACHHANG.HIEU = LEFT(t2.HIEUDH,3), KHACHHANG.SOTHAN= t2.SOTHANDH  ,KHACHHANG.VITRI=t2.VITRIDHN
FROM KHACHHANG INNER JOIN  
 ( 
   SELECT DANHBO,HIEUDH,SOTHANDH, VITRIDHN
   FROM  CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG
   WHERE SOTHANDH IS NOT NULL
) as t2  
ON	KHACHHANG.DANHBA = t2.DANHBO