UPDATE HANDHELD
SET  HOPDONG = tb1.HOPDONG,
	 TENKH = tb1.HOTEN,
	 SONHA = tb1.SONHA,
	 TENDUONG = tb1.TENDUONG,
	 PHUONG = tb1.PHUONG,	
	 QUAN = tb1.QUAN
 FROM TB_DULIEUKHACHHANG tb1
 WHERE tb1.DANHBO=HANDHELD.DANHBO
