--SELECT DHN_SOBANGKE,DHN_TODS, DHN_SOTHAN FROM TB_THAYDHN WHERE DHN_SOTHAN IS NULL

UPDATE TB_THAYDHN
SET  DHN_SOTHAN = SOTHANDH
FROM TB_DULIEUKHACHHANG
WHERE TB_THAYDHN.DHN_DANHBO = TB_DULIEUKHACHHANG.DANHBO
AND	DHN_SOBANGKE='12020' AND DHN_TODS='TB02'