UPDATE TB_DULIEUKHACHHANG
SET TB_DULIEUKHACHHANG.HIEUDH = LEFT(t2.HCT_HIEUDHNGAN,3), TB_DULIEUKHACHHANG.CODH=t2.HCT_CODHNGAN
,TB_DULIEUKHACHHANG.SOTHANDH= t2.HCT_SOTHANGAN  ,
TB_DULIEUKHACHHANG.NGAYKIEMDINH= t2.HCT_NGAYKIEMDINH,NGAYTHAY=t2.HCT_NGAYGAN,CAP=t2.HCT_CAP,CHITHAN=t2.HCT_CHITHAN,CHIGOC=t2.HCT_CHIGOC,
BAOTHAY='False'
FROM TB_DULIEUKHACHHANG INNER JOIN  
 ( 
   SELECT  DHN_DANHBO, HCT_HIEUDHNGAN, HCT_CODHNGAN, HCT_CAP, HCT_SOTHANGAN, HCT_NGAYGAN, HCT_NGAYKIEMDINH, HCT_CHITHAN, HCT_CHIGOC
   FROM  TB_THAYDHN
   WHERE HCT_TRONGAI = 'False'
) as t2  
ON	TB_DULIEUKHACHHANG.DANHBO = t2.DHN_DANHBO