INSERT INTO KHACHHANG (MAQUAN,MAPHUONG,TODS, MAY, DOT, DANHBA, HOPDONG, TENKH, SO, DUONG, GB, DM, TILESH, TILEHCSN, TILESX, TILEKD, MALOTRINH,MALOTRINH2, HIEULUCKY, NAM, NGAYGAN, CHISO, TIEUTHU, CODE,HIEU,SOTHAN)
SELECT kh.QUAN AS MAQUAN ,kh.PHUONG AS MAPHUONG ,'3' AS TODS,SUBSTRING(LOTRINH,3,2) AS MAY,SUBSTRING(LOTRINH,1,2) AS DOT,kh.DANHBO AS DANHBA,HOPDONG,
	   kh.HOTEN as TENKH,kh.SONHA as SO, kh.TENDUONG as DUONG, kh.GIABIEU AS GB, kh.DINHMUC AS DM, '0' AS TILESH, '0' AS TILEHCSN, '0' AS TILESX, '0' AS TILEKD ,
	   kh.LOTRINH AS MALOTRINH , kh.LOTRINH AS MALOTRINH2 , convert(varchar(20),kh.KY)+'/'+convert(varchar(20),kh.NAM) AS HIEULUCKY, kh.NAM AS NAM,
	   kh.NGAYTHAY AS NGAYGAN, kh.CHISOKYTRUOC AS CHISO, '0' AS TIEUTHU, kh.CODE AS CODE, HIEUDH AS HIEU, SOTHANDH AS SOTHAN
FROM  CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG kh 
WHERE kh.KY= 7 AND  kh.DANHBO NOT IN (SELECT DANHBA FROM DocSo_PHT.dbo.KHACHHANG)

SELECT * FROM DocSo_PHT.dbo.KHACHHANG  WHERE DANHBA='13031135448'
SELECT * FROM DocSo_PHT.dbo.DS2012  WHERE DANHBA='13031135448'

-- CAP NHAT LO TRINH

UPDATE TB_DULIEUKHACHHANG SET  LOTRINH=t2.LOTRINH
FROM CAPNUOCTANHOA.dbo.HANDHELD as t2
WHERE TB_DULIEUKHACHHANG.DANHBO = t2.DANHBO
  AND LEFT(t2.LOTRINH,4) IN ('0109','0106')
  
  
UPDATE KHACHHANG SET  MALOTRINH=t2.LOTRINH ,MALOTRINH2=t2.LOTRINH
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE KHACHHANG.DANHBA = t2.DANHBO

  AND LEFT(t2.LOTRINH,4) IN ('0109','0106')
  
SELECT LEFT(t2.LOTRINH,4)
FROM KHACHHANG as t2


select SUBSTRING(MALOTRINH,3,2) from  dbo.KHACHHANG where LEFT(MALOTRINH,4)='0718'

UPDATE dbo.KHACHHANG SET MALOTRINH2=MALOTRINH


-- UPDATE CHISONUOC
UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI, TB_DULIEUKHACHHANG.CODE=DocSo_PHT.dbo.DS2012.CODE
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI
		AND DocSo_PHT.dbo.DS2012.KY ='06'
		
		
---- CAP NHAT SONHA + TEN DUONG

UPDATE KHACHHANG SET  SO=t2.SONHA ,DUONG=t2.TENDUONG
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE KHACHHANG.DANHBA = t2.DANHBO

--- KIEM TRA SO LUONG DHN

-- TAN BINH 01
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')
ORDER BY MALOTRINH ASC
-- TAN BINH 02
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('16','17','18','19','20','21','22','23','24','25','26','27','28','29','30')
ORDER BY MALOTRINH ASC
-- TAN PHU
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46')
ORDER BY MALOTRINH ASC

------


UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='1' WHERE SUBSTRING(MALOTRINH,3,2) IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='2' WHERE SUBSTRING(MALOTRINH,3,2) IN ('16','17','18','19','20','21','22','23','24','25','26','27','28','29','30')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='3' WHERE SUBSTRING(MALOTRINH,3,2) IN ('31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET MAY=SUBSTRING(MALOTRINH,3,2) 

SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2)='35'




