 UPDATE TB_DULIEUKHACHHANG
 SET KHU = HdTH02.KHU, 
	 HOPDONG = HdTH02.HOPDONG,
	 CODEFU=HdTH02.CODEFU,
	 CHUKY=HdTH02.CHUKY,
	 CHITHAN='CON',
	 CHIGOC='CON',	
	 CREATEDATE = GETDATE(), CREATEBY='system'
 FROM HdTH02
 WHERE TB_DULIEUKHACHHANG.DANHBO=HdTH02.DANHBO


 

SELECT COUNT(*) from TB_DULIEUKHACHHANG WHERE HOPDONG IS NULL ORDER BY HOPDONG ASC

SELECT HIEUDH FROM TB_DULIEUKHACHHANG
GROUP BY HIEUDH

