UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI
		AND DocSo_PHT.dbo.DS2012.KY ='05'

 