 
 UPDATE TB_DULIEUKHACHHANG SET  GIABIEU=GB, DINHMUC=DM  
 FROM DocSo_PHT.dbo.DS2012  WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA   AND CSMOI IS NOT NULL  AND CSCU<=CSMOI 
 AND DocSo_PHT.dbo.DS2012.KY ='7' 
 
 UPDATE HOADONTH05 SET  KHU= t2.LOTRINH , Field37=t2.HIEUDH 
FROM TB_DULIEUKHACHHANG t2
WHERE HOADONTH05.DANHBO = t2.DANHBO

SELECT KHU AS LOTRINH, DOT, DANHBO, CODH, HOPDONG, TENKH, SONHA, DUONG, GIABIEU, DINHMUC, KY, NAM, CODE, CODEF, CSCU, CSMOI, RT, CHUKY, LNCC, LNCT, Field36, Field37, QUAN, PHUONG FROM HOADONTH05 WHERE GIABIEU=15 AND LEFT(Field37,3) <> 'KEN'
ORDER BY LOTRINH ASC 

---------------- C?P NH?T GHI CHÚ --------------------

SELECT NGAYCN,DB,
CASE LDon
         WHEN 'DM' THEN N'?i?u Ch?nh ??nh M?c T? '+ convert(varchar(20),DM) +' -> ' +convert(varchar(20),DMDC)   
         WHEN 'GB' THEN N'?i?u Ch?nh Giá Bi?u T?  '+ convert(varchar(20),GB) +' -> ' +convert(varchar(20),GBDC)       
END AS 'NOIDUNG'
FROM [CAPNUOCTANHOA].[dbo].[Bang_Ke_Dieu_Chinh_Table]
WHERE NAM in ('2009','2010','2011','2012')  AND LDon IN ('GB') 

SELECT  HCT_NGAYGAN,DHN_DANHBO,
CASE DHN_LOAIBANGKE
         WHEN 'DK' THEN N'Thay ?HN ??nh K?'   
         WHEN 'BB' THEN N'Thay ?HN ' + DHN_LYDOTHAY     
         WHEN 'BT' THEN N'Thay ?HN B?i Th??ng'   
         WHEN 'DC' THEN N'Thay ?HN ??t Chì'
         WHEN 'KM' THEN N'Thay ?HN Kính M?'   
         WHEN 'NG' THEN N'Thay ?HN Ng?ng'     
END AS 'NOIDUNG'
FROM  TB_THAYDHN
WHERE HCT_TRONGAI = 'False' AND HCT_NGAYGAN IS NOT NULL
------------------------

INSERT INTO TB_GHICHU (DANHBO,NOIDUNG,DONVI, CREATEDATE)
SELECT DB as DANHBO,
CASE LDon
         WHEN 'DM' THEN N'?i?u Ch?nh ??nh M?c T? '+ convert(varchar(20),DM) +' -> ' +convert(varchar(20),DMDC)   
         WHEN 'GB' THEN N'?i?u Ch?nh Giá Bi?u T?  '+ convert(varchar(20),GB) +' -> ' +convert(varchar(20),GBDC)       
END AS NOIDUNG,'KTKS' as DONVI,NGAYCN AS CREATEDATE
FROM [CAPNUOCTANHOA].[dbo].[Bang_Ke_Dieu_Chinh_Table]
WHERE NAM in ('2009','2010','2011','2012')  AND LDon IN ('GB','DM') 

---------------------------
INSERT INTO TB_GHICHU (DANHBO,NOIDUNG,DONVI, CREATEDATE)
SELECT  DHN_DANHBO AS DANHBO,
CASE DHN_LOAIBANGKE
         WHEN 'DK' THEN N'Thay ?HN ??nh K?'   
         WHEN 'BB' THEN N'Thay ?HN ' + DHN_LYDOTHAY     
         WHEN 'BT' THEN N'Thay ?HN B?i Th??ng'   
         WHEN 'DC' THEN N'Thay ?HN ??t Chì'
         WHEN 'KM' THEN N'Thay ?HN Kính M?'   
         WHEN 'NG' THEN N'Thay ?HN Ng?ng'     
END AS 'NOIDUNG','DHN' as DONVI,HCT_NGAYGAN AS CREATEDATE
FROM  TB_THAYDHN
WHERE HCT_TRONGAI = 'False' AND HCT_NGAYGAN IS NOT NULL

----------------------------------
-- SUA SO LIEU 
SELECT * FROM TB_DULIEUKHACHHANG WHERE DANHBO='13182451016'
SELECT * FROM TB_GANMOI WHERE DANHBO='13182451016'
SELECT * FROM TB_YEUCAUDC WHERE DANHBO='13182451016'

UPDATE TB_DULIEUKHACHHANG SET DANHBO='13182451016' WHERE DANHBO='13192451016'
UPDATE TB_GANMOI SET DANHBO='13182451016' WHERE DANHBO='13192451016'
UPDATE TB_YEUCAUDC SET DANHBO='13182451016' WHERE DANHBO='13192451016'

--- BAO THAY

INSERT INTO BAOTHAYDHN (DANHBA, TENKH, SO, DUONG, HIEUMOI, COMOI, NGAYTHAY, CSGO, CSGAN, SOTHANMOI, VITRIMOI, MACHITHAN, MACHIGOC, LOAI)
SELECT DHN_DANHBO,HOTEN, SONHA,TENDUONG,LEFT(HCT_HIEUDHNGAN,3),HCT_CODHNGAN,HCT_NGAYGAN,HCT_CHISOGO,HCT_CHISOGAN,HCT_SOTHANGAN,VITRIDHN,HCT_CHITHAN,HCT_CHIGOC,(case when DHN_LOAIBANGKE='DK' then 1 else 2 end) AS LOAI
FROM CAPNUOCTANHOA.dbo.TB_THAYDHN thay,CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG kh
WHERE thay.DHN_DANHBO= kh.DANHBO AND HCT_TRONGAI='False'

INSERT INTO KHACHHANG (MAQUAN,MAPHUONG,TODS, MAY, DOT, DANHBA, HOPDONG, TENKH, SO, DUONG, GB, DM, TILESH, TILEHCSN, TILESX, TILEKD, MALOTRINH,MALOTRINH2, HIEULUCKY, NAM, NGAYGAN, CHISO, TIEUTHU, CODE,HIEU,SOTHAN)
SELECT kh.QUAN AS MAQUAN ,kh.PHUONG AS MAPHUONG ,'3' AS TODS,SUBSTRING(LOTRINH,3,2) AS MAY,SUBSTRING(LOTRINH,1,2) AS DOT,kh.DANHBO AS DANHBA,HOPDONG,
	   kh.HOTEN as TENKH,kh.SONHA as SO, kh.TENDUONG as DUONG, kh.GIABIEU AS GB, kh.DINHMUC AS DM, '0' AS TILESH, '0' AS TILEHCSN, '0' AS TILESX, '0' AS TILEKD ,
	   kh.LOTRINH AS MALOTRINH , kh.LOTRINH AS MALOTRINH2 , convert(varchar(20),kh.KY)+'/'+convert(varchar(20),kh.NAM) AS HIEULUCKY, kh.NAM AS NAM,
	   kh.NGAYTHAY AS NGAYGAN, kh.CHISOKYTRUOC AS CHISO, '0' AS TIEUTHU, kh.CODE AS CODE, HIEUDH AS HIEU, SOTHANDH AS SOTHAN
FROM  CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG kh 
WHERE kh.KY= 7 AND  kh.DANHBO NOT IN (SELECT DANHBA FROM DocSo_PHT.dbo.KHACHHANG)

SELECT * FROM DocSo_PHT.dbo.KHACHHANG  WHERE DANHBA='13031135448'
SELECT * FROM DocSo_PHT.dbo.DS2012  WHERE DANHBA='13031135448'

-- CAP NHAT LO TRINH

UPDATE TB_DULIEUKHACHHANG SET  LOTRINH=t2.LOTRINH
FROM CAPNUOCTANHOA.dbo.HANDHELD as t2
WHERE TB_DULIEUKHACHHANG.DANHBO = t2.DANHBO
  AND LEFT(t2.LOTRINH,4) IN ('0109','0106')
  
  
UPDATE DocSo_PHT.dbo.KHACHHANG SET  MALOTRINH=t2.LOTRINH ,MALOTRINH2=t2.LOTRINH, DOT= LEFT(t2.LOTRINH,2), MAY=SUBSTRING(MALOTRINH,3,2), TODS=''
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2

WHERE KHACHHANG.DANHBA = t2.DANHBO and DocSo_PHT.dbo.KHACHHANG.DANHBA='13172418757'


select * from KHACHHANG where DANHBA='13172418757'
  AND LEFT(t2.LOTRINH,4) IN ('0109','0106')
  
SELECT LEFT(t2.LOTRINH,4)
FROM KHACHHANG as t2


select SUBSTRING(MALOTRINH,3,2) from  dbo.KHACHHANG where LEFT(MALOTRINH,4)='0718'

UPDATE dbo.KHACHHANG SET MALOTRINH2=MALOTRINH


-- UPDATE CHISONUOC

UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI, TB_DULIEUKHACHHANG.CODE=DocSo_PHT.dbo.DS2012.CODE
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSCU<=CSMOI
		AND DocSo_PHT.dbo.DS2012.KY =7
		
 MONTH(GETDATE())
		
		
---- CAP NHAT SONHA + TEN DUONG

UPDATE DocSo_PHT.dbo.KHACHHANG SET  SO=t2.SONHA ,DUONG=t2.TENDUONG
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE DANHBA = t2.DANHBO

--- KIEM TRA SO LUONG DHN

-- TAN BINH 01
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')
ORDER BY MALOTRINH ASC
-- TAN BINH 02
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('16','17','18','19','20','21','22','23','24','25','26','27','28','29','30')
ORDER BY MALOTRINH ASC
-- TAN PHU
SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2) IN ('31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46')
ORDER BY MALOTRINH ASC

------


UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='1' WHERE SUBSTRING(MALOTRINH,3,2) IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='2' WHERE SUBSTRING(MALOTRINH,3,2) IN ('16','17','18','19','20','21','22','23','24','25','26','27','28','29','30')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET TODS='3' WHERE SUBSTRING(MALOTRINH,3,2) IN ('31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46')

UPDATE DocSo_PHT.dbo.KHACHHANG  SET MAY=SUBSTRING(MALOTRINH,3,2) 

SELECT * FROM DocSo_PHT.dbo.KHACHHANG WHERE LEFT(MALOTRINH,2)='09' AND SUBSTRING(MALOTRINH,3,2)='35'


----- CAP NHAT DOT

UPDATE dbo.TB_DULIEUKHACHHANG SET DOT=LEFT(LOTRINH,2)


-- UPDATE CHISONUOC
UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI, TB_DULIEUKHACHHANG.CODE=DocSo_PHT.dbo.DS2012.CODE
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI
		AND DocSo_PHT.dbo.DS2012.KY ='05'
		
-- UPDATE LO TRINH
UPDATE KHACHHANG SET  MALOTRINH=t2.LOTRINH ,MALOTRINH2=t2.LOTRINH
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE KHACHHANG.DANHBA = t2.DANHBO
  AND len(MALOTRINH)<9

SELECT * FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE LEFT(t2.LOTRINH,2) IN ('01','02','03','04','05','06','07','08','09','10')

-- UPDATE SO MAY

UPDATE KHACHHANG SET MAY = SUBSTRING(MALOTRINH,3,2) 

SELECT * FROM DS2012  WHERE KY=6 AND LEN(MALOTRINH)<9


UPDATE KHACHHANG
SET KHACHHANG.HIEU = LEFT(t2.HIEUDH,3), KHACHHANG.SOTHAN= t2.SOTHANDH  ,KHACHHANG.VITRI=t2.VITRIDHN
FROM KHACHHANG INNER JOIN  
 ( 
   SELECT DANHBO,HIEUDH,SOTHANDH, VITRIDHN
   FROM  CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG
   WHERE SOTHANDH IS NOT NULL
) as t2  
ON	KHACHHANG.DANHBA = t2.DANHBO


UPDATE KHACHHANG
SET  HOPDONG = tb1.HOPDONG,
	 TENKH = tb1.HOTEN,
	 SONHA = tb1.SONHA,
	 TENDUONG = tb1.TENDUONG,
	 PHUONG = tb1.PHUONG,	
	 QUAN = tb1.QUAN
 FROM TB_DULIEUKHACHHANG tb1
 WHERE tb1.DANHBO=HANDHELD.DANHBO