-- TAN BINH 01
UPDATE HANDHELD
SET  HOPDONG = tb1.HOPDONG,
	 TENKH = tb1.HOTEN,
	 SONHA = tb1.SONHA,
	 TENDUONG = tb1.TENDUONG,
	 PHUONG = tb1.PHUONG,	
	 QUAN = tb1.QUAN
 FROM TB_DULIEUKHACHHANG tb1
 WHERE tb1.DANHBO = HANDHELD.DANHBO 
AND ((LEFT(tb1.DANHBO,7) >= '1301101' AND LEFT(tb1.DANHBO,7) <= '1311385') OR (LEFT(tb1.DANHBO,7) >= '1210186' AND LEFT(tb1.DANHBO,7) <= '1214210'))


SELECT DISTINCT * FROM TB_DULIEUKHACHHANG tb1
WHERE ((LEFT(tb1.DANHBO,7) >= '1301101' AND LEFT(tb1.DANHBO,7) <= '1311385') OR (LEFT(tb1.DANHBO,7) >= '1210186' AND LEFT(tb1.DANHBO,7) <= '1214210'))
AND ( HIEUDH IS NULL OR HIEUDH='' 
	OR SOTHANDH IS NULL OR SOTHANDH='' 
	OR SOTHANDH LIKE '%o%' OR SOTHANDH LIKE '%CMS%' OR SOTHANDH LIKE '% %' OR SOTHANDH LIKE '%K%'
OR NGAYTHAY IS NULL)


-- TAN BINH 02
UPDATE HANDHELD
SET  HOPDONG = tb1.HOPDONG,
	 TENKH = tb1.HOTEN,
	 SONHA = tb1.SONHA,
	 TENDUONG = tb1.TENDUONG,
	 PHUONG = tb1.PHUONG,	
	 QUAN = tb1.QUAN
 FROM TB_DULIEUKHACHHANG tb1
 WHERE tb1.DANHBO = HANDHELD.DANHBO AND (((LEFT(tb1.DANHBO,7) >= '1312000' AND LEFT(tb1.DANHBO,7) <= '1315220') OR (LEFT(tb1.DANHBO,7) >= '1322288' AND LEFT(tb1.DANHBO,7) <= '1326999')) AND LEFT(tb1.DANHBO,7) NOT IN ('1314197','1314198')) 

SELECT * FROM TB_DULIEUKHACHHANG tb1
WHERE (((LEFT(tb1.DANHBO,7) >= '1312000' AND LEFT(tb1.DANHBO,7) <= '1315220') OR (LEFT(tb1.DANHBO,7) >= '1322288' AND LEFT(tb1.DANHBO,7) <= '1326999')) AND LEFT(tb1.DANHBO,7) NOT IN ('1314197','1314198')) 
AND ( HIEUDH IS NULL OR HIEUDH='' 
	OR SOTHANDH IS NULL OR SOTHANDH='' 
	OR SOTHANDH LIKE '%o%' OR SOTHANDH LIKE '%CMS%' OR SOTHANDH LIKE '% %' OR SOTHANDH LIKE '%K%'
OR NGAYTHAY IS NULL)

-- TAN PHU
UPDATE HANDHELD
SET  HOPDONG = tb1.HOPDONG,
	 TENKH = tb1.HOTEN,
	 SONHA = tb1.SONHA,
	 TENDUONG = tb1.TENDUONG,
	 PHUONG = tb1.PHUONG,	
	 QUAN = tb1.QUAN
 FROM TB_DULIEUKHACHHANG tb1
 WHERE tb1.DANHBO = HANDHELD.DANHBO AND ((LEFT(tb1.DANHBO,7) >= '1315221' AND LEFT(tb1.DANHBO,7) <= '1321999') OR LEFT(tb1.DANHBO,7) = '1314197'  OR LEFT(tb1.DANHBO,7) = '1314198')

SELECT * FROM TB_DULIEUKHACHHANG tb1
WHERE ((LEFT(tb1.DANHBO,7) >= '1315221' AND LEFT(tb1.DANHBO,7) <= '1321999') OR LEFT(tb1.DANHBO,7) = '1314197'  OR LEFT(tb1.DANHBO,7) = '1314198')
AND ( HIEUDH IS NULL OR HIEUDH='' 
	OR SOTHANDH IS NULL OR SOTHANDH='' 
	OR SOTHANDH LIKE '%o%' OR SOTHANDH LIKE '%CMS%' OR SOTHANDH LIKE '% %' OR SOTHANDH LIKE '%K%'
OR NGAYTHAY IS NULL)

-- trung lo trinh

SELECT DANHBO FROM TB_DULIEUKHACHHANG
GROUP BY DANHBO
HAVING COUNT(LOTRINH)>=2
ORDER BY DANHBO ASC

SELECT LOTRINH FROM TB_DULIEUKHACHHANG 
GROUP BY LOTRINH HAVING COUNT(LOTRINH)>=2 ORDER BY LOTRINH ASC

SELECT LOTRINH FROM TB_DULIEUKHACHHANG WHERE LOTRINH='013509304'

SELECT DANHBO FROM TB_YEUCAUDC
GROUP BY DANHBO
HAVING COUNT(DANHBO)>=2
ORDER BY DANHBO ASC

SELECT DANHBO,LOTRINH,HOTEN,(SONHA+' '+TENDUONG) as 'DIACHI' 
FROM  TB_DULIEUKHACHHANG 
GROUP BY  DANHBO,LOTRINH,HOTEN,(SONHA+' '+TENDUONG) 
HAVING COUNT(LOTRINH)>=2 ORDER BY LOTRINH ASC