  
  

ALTER PROCEDURE sp_ThongTin
(@DANHBO VARCHAR(50),
	@QUAN VARCHAR(50) OUTPUT,
	@PHUONG FLOAT OUTPUT,
	@CODH FLOAT OUTPUT,
	@MADMA FLOAT OUTPUT) 
AS
BEGIN
    IF EXISTS( SELECT DANHBO FROM TB_DULIEUKHACHHANG WHERE DANHBO=@DANHBO)
       BEGIN
              SELECT @QUAN=kh.QUAN,@PHUONG=p.MAPHUONG,@CODH=kh.CODH,@MADMA=kh.MADMA  FROM  TB_DULIEUKHACHHANG kh,  PHUONG p, QUAN q WHERE kh.DANHBO=@DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG
       END
     ELSE
        BEGIN
            SELECT TOP(1) @QUAN=kh.QUAN,@PHUONG=p.MAPHUONG,@CODH=kh.CODH,@MADMA=kh.MADMA  FROM  TB_DULIEUKHACHHANG_HUYDB kh,  PHUONG p, QUAN q WHERE kh.DANHBO=@DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG ORDER BY CREATEDATE DESC
        END
END