UPDATE TB_VATUTHAY_DONGIA
SET TENVT=TB_VATUTHAY.TENVT
FROM TB_VATUTHAY
WHERE TB_VATUTHAY.MAVT=TB_VATUTHAY_DONGIA.MAVT

UPDATE TB_VATUTHAY_DHN
SET TENVT=TB_VATUTHAY.TENVT
FROM TB_VATUTHAY
WHERE TB_VATUTHAY.MAVT=TB_VATUTHAY_DHN.MAVT


SELECT MAVT,SUM(SOLUONG)
FROM TB_VATUTHAY_DHN 
WHERE DOTTHAY='TB01-14367'
GROUP BY MAVT


----- TONG

SELECT vt.MAVT,dg.TENVT,vt.DVT, dg.DGVATLIEU,dg.DGNHANCONG,SUM(SOLUONG) AS SOLUONG,
CASE WHEN vt.MAVT ='CVIEN' THEN (SUM(SOLUONG)/200)* dg.DGVATLIEU  WHEN vt.MAVT ='DDONG' THEN (SUM(SOLUONG)/340)*dg.DGVATLIEU ELSE  SUM(SOLUONG)*dg.DGVATLIEU END AS VATLIEU,
SUM(SOLUONG)*dg.DGNHANCONG AS NHANCONG
FROM TB_VATUTHAY_DHN vt , TB_VATUTHAY_DONGIA dg
WHERE vt.MAVT=dg.MAVT and DOTTHAY='TB01-14367'
GROUP BY  vt.MAVT,dg.TENVT,vt.DVT,dg.DGVATLIEU,dg.DGNHANCONG

-- TUNG DANHBO

SELECT MAVT,SUM(SOLUONG)
FROM TB_VATUTHAY_DHN 
WHERE DOTTHAY='TB01-14367'
GROUP BY MAVT

 SELECT vt.ID_BAOTHAY,vt.MAVT,dg.DGVATLIEU,dg.DGNHANCONG,SUM(SOLUONG) AS SOLUONG,
	CASE WHEN vt.MAVT ='CVIEN' THEN (SUM(SOLUONG)/200)* dg.DGVATLIEU  WHEN vt.MAVT ='DDONG' THEN (SUM(SOLUONG)/340)*dg.DGVATLIEU ELSE  SUM(SOLUONG)*dg.DGVATLIEU END AS VATLIEU,
	SUM(SOLUONG)*dg.DGNHANCONG  AS NHANCONG
	FROM TB_VATUTHAY_DHN vt , TB_VATUTHAY_DONGIA dg
	WHERE vt.MAVT=dg.MAVT and ID_BAOTHAY='117473'
	GROUP BY vt.ID_BAOTHAY,vt.MAVT,dg.DGVATLIEU,dg.DGNHANCONG



UPDATE TB_THAYDHN 
SET  TENKH =KH.HOTEN
	,DIACHI=KH.SONHA + ' ' + KH.TENDUONG,LOTRINH=KH.LOTRINH
FROM TB_DULIEUKHACHHANG KH
WHERE KH.DANHBO= TB_THAYDHN.DHN_DANHBO


SELECT thay.TENKH,thay.DIACHI,thay.DHN_DANHBO,(thay.HCT_HIEUDHNGAN + ' - ' + thay.HCT_CODHNGAN+' Ly') as DHN,
ROUND(dg.VATLIEU,2) AS VL,ROUND(dg.NHANCONG,2) AS NC,(ROUND(dg.VATLIEU,2) + ROUND(dg.NHANCONG,2)) AS TC,CONVERT(VARCHAR(20),thay.HCT_NGAYGAN,103) AS NGAYGAN
FROM TB_THAYDHN thay,
(
	SELECT t.ID_BAOTHAY,SUM(VATLIEU) AS VATLIEU,SUM(NHANCONG)AS NHANCONG
	FROM 
	   ( SELECT vt.ID_BAOTHAY,vt.MAVT,dg.DGVATLIEU,dg.DGNHANCONG,SUM(SOLUONG) AS SOLUONG,
		CASE WHEN vt.MAVT ='CVIEN' THEN (SUM(SOLUONG)/200)* dg.DGVATLIEU  WHEN vt.MAVT ='DDONG' THEN (SUM(SOLUONG)/340)*dg.DGVATLIEU ELSE  SUM(SOLUONG)*dg.DGVATLIEU END AS VATLIEU,
		SUM(SOLUONG)*dg.DGNHANCONG  AS NHANCONG
		FROM TB_VATUTHAY_DHN vt , TB_VATUTHAY_DONGIA dg
		WHERE vt.MAVT=dg.MAVT and DOTTHAY='TB01-14367'
		GROUP BY vt.ID_BAOTHAY,vt.MAVT,dg.DGVATLIEU,dg.DGNHANCONG
		) AS t
	GROUP BY t.ID_BAOTHAY
) as dg
WHERE thay.ID_BAOTHAY=dg.ID_BAOTHAY









SELECT MAVT, COUNT(*)
FROM TB_VATUTHAY_DHN
WHERE DOTTHAY='TB01-14367' AND MAVT LIKE 'TLK%'
GROUP BY MAVT

SELECT * FROM TB_VATUTHAY_DONGIA WHERE MAVT='TLK15ITR'