select * from TB_THAYDHN order by HCT_NGAYGAN desc

SELECT LEFT(HIEUDH,3),COUNT(*)
FROM TB_DULIEUKHACHHANG
GROUP BY LEFT(HIEUDH,3)

SELECT * FROM TB_DULIEUKHACHHANG WHERE HIEUDH IS NULL

UPDATE TB_DULIEUKHACHHANG
SET HIEUDH=TB_THAYDHN.HCT_HIEUDHNGAN,
	NGAYTHAY=TB_THAYDHN.HCT_NGAYGAN,
	SOTHANDH=TB_THAYDHN.HCT_SOTHANGAN,
	NGAYKIEMDINH = TB_THAYDHN.HCT_NGAYKIEMDINH,
	CODH=TB_THAYDHN.HCT_CODHNGAN
FROM TB_THAYDHN
WHERE TB_DULIEUKHACHHANG.DANHBO=TB_THAYDHN.DHN_DANHBO
AND  TB_THAYDHN.DHN_DANHBO='13041800166' AND TB_THAYDHN.DHN_TODS='DA'
	

select * from TB_THAYDHN WHERE DHN_DANHBO='13162271355'

UPDATE TB_DULIEUKHACHHANG
SET HIEUDH=TB_THAYDHN.HCT_HIEUDHNGAN,
	NGAYTHAY=TB_THAYDHN.HCT_NGAYGAN,
	SOTHANDH=TB_THAYDHN.HCT_SOTHANGAN,
	NGAYKIEMDINH = TB_THAYDHN.HCT_NGAYKIEMDINH,
	CODH=TB_THAYDHN.HCT_CODHNGAN,
	CHIGOC=TB_THAYDHN.HCT_CHIGOC,
	CHITHAN=TB_THAYDHN.HCT_CHITHAN	
FROM TB_THAYDHN
WHERE TB_DULIEUKHACHHANG.DANHBO=TB_THAYDHN.DHN_DANHBO
AND  ID_BAOTHAY='230402'