select * from TB_THAYDHN order by HCT_NGAYGAN desc

SELECT LEFT(HIEUDH,3),COUNT(*)
FROM TB_DULIEUKHACHHANG
GROUP BY LEFT(HIEUDH,3)

SELECT * FROM TB_DULIEUKHACHHANG WHERE HIEUDH IS NULL

UPDATE TB_DULIEUKHACHHANG
SET HIEUDH=TB_THAYDHN.DHN_HIEUDHN,
	NGAYTHAY=TB_THAYDHN.DHN_NGAYGAN,
	SOTHANDH=TB_THAYDHN.DHN_SOTHAN,
	CODH=TB_THAYDHN.DHN_CODH
FROM TB_THAYDHN
WHERE TB_DULIEUKHACHHANG.DANHBO=TB_THAYDHN.DHN_DANHBO
AND  TB_THAYDHN.DHN_DANHBO='13041800166' AND TB_THAYDHN.DHN_TODS='DA'
	

1320-269-6102