UPDATE TB_DULIEUKHACHHANG SET  CODH=t2.CoDh
FROM HoadonTH04 t2
WHERE TB_DULIEUKHACHHANG.DANHBO = t2.DANHBO

UPDATE TB_DULIEUKHACHHANG SET  GIABIEU=t2.Giabieu,DINHMUC=t2.DinhMuc
FROM HoadonTH04 t2
WHERE TB_DULIEUKHACHHANG.DANHBO = t2.DANHBO
