DROP PROC BC_TONGKET

CREATE PROC BC_TONGKET
	@TUNGAY VARCHAR(50),
	@DENNGAY VARCHAR(50),
	@HIEULUC	VARCHAR(50)
 AS
 
	UPDATE BAOCAO_TONGKET SET  AMSAU = 0,GANHOPBV =0, TLKDUTCHI = 0,CHUYENDINHMUC_SH = 0,CHUYENDINHMUC_KD = 0,GANMOI = 0,TAILAP = 0 ,HUYDB = 0
	
 
	 UPDATE BAOCAO_TONGKET SET  AMSAU =  t.TS
	 FROM  (SELECT COUNT(*) AS TS FROM TB_DHNAMSAU WHERE CONVERT(DATETIME,NGAYLAP,103) BETWEEN CONVERT(DATETIME,@TUNGAY,103) AND CONVERT(DATETIME,@DENNGAY,103)) AS t
	 
	
	 UPDATE BAOCAO_TONGKET SET  GANHOPBV =  t.TS
	 FROM (SELECT COUNT(*)AS TS FROM TB_GANHOPBV WHERE CONVERT(DATETIME,NGAYLAP,103) BETWEEN CONVERT(DATETIME,@TUNGAY,103) AND CONVERT(DATETIME,@DENNGAY,103)) AS t
	 
	 
	 UPDATE BAOCAO_TONGKET SET  TLKDUTCHI =  t.TS
	 FROM (SELECT COUNT(*)AS TS FROM TB_TLKDUTCHI WHERE CONVERT(DATETIME,NGAYBAO,103) BETWEEN CONVERT(DATETIME,@TUNGAY,103) AND CONVERT(DATETIME,@DENNGAY,103)) AS t
	 

	 
	 UPDATE BAOCAO_TONGKET SET  CHUYENDINHMUC_SH =  t.TS
	 FROM (SELECT COUNT(*)AS TS FROM TB_CHUYENDINHMUC WHERE CONVERT(DATETIME,NGAYLAP,103) BETWEEN CONVERT(DATETIME,@TUNGAY,103) AND CONVERT(DATETIME,@DENNGAY,103) AND REPLACE(CONGDUNG,' ','') LIKE 'SINHH%') AS t
	 

	 UPDATE BAOCAO_TONGKET SET  CHUYENDINHMUC_KD =  t.TS
	 FROM (SELECT COUNT(*)AS TS FROM TB_CHUYENDINHMUC WHERE CONVERT(DATETIME,NGAYLAP,103) BETWEEN CONVERT(DATETIME,@TUNGAY,103) AND CONVERT(DATETIME,@DENNGAY,103) AND REPLACE(CONGDUNG,' ','') NOT LIKE 'SINHH%') AS t
	 


	UPDATE BAOCAO_TONGKET SET  GANMOI =  t.TS
	 FROM (SELECT COUNT(*) AS TS FROM TB_GANMOI WHERE HIEULUC=@HIEULUC AND SHS NOT LIKE '%D%') AS t
	 
	 
	 UPDATE BAOCAO_TONGKET SET  TAILAP =  t.TS
	 FROM (SELECT COUNT(*) AS TS FROM TB_GANMOI WHERE HIEULUC=@HIEULUC AND SHS  LIKE '%D%') AS t
	 
	 
	 UPDATE BAOCAO_TONGKET SET  HUYDB =  t.TS
	 FROM (SELECT COUNT(*) AS TS FROM TB_DULIEUKHACHHANG_HUYDB WHERE HIEULUCHUY=@HIEULUC) AS t

GO



