-- TAN BINH 02
SELECT DANHBO,HOTEN, (SONHA+' '+TENDUONG) AS 'DIACHI', HIEUDH, SOTHANDH FROM dbo.TB_DULIEUKHACHHANG
WHERE (SOTHANDH LIKE '%o%' OR SOTHANDH LIKE '%CMS%' ) AND ((LEFT(DANHBO,7) >= '1312000' AND LEFT(DANHBO,7) <= '1315220') OR (LEFT(DANHBO,7) >= '1322000' AND LEFT(DANHBO,7) <= '1326999'))

-- TAN BINH 02
SELECT DANHBO,HOTEN, (SONHA+' '+TENDUONG) AS 'DIACHI', HIEUDH, SOTHANDH FROM dbo.TB_DULIEUKHACHHANG
WHERE (SOTHANDH LIKE '%o%' OR SOTHANDH LIKE '%CMS%' ) AND (LEFT(DANHBO,7) >= '1301' AND LEFT(DANHBO,7) <= '1311')
