-- UPDATE CHISONUOC
UPDATE TB_DULIEUKHACHHANG SET  CHISOKYTRUOC= CSMOI, TB_DULIEUKHACHHANG.CODE=DocSo_PHT.dbo.DS2012.CODE
FROM DocSo_PHT.dbo.DS2012 
WHERE TB_DULIEUKHACHHANG.DANHBO = DocSo_PHT.dbo.DS2012.DANHBA
	  AND CSMOI IS NOT NULL  AND CSMOI > 0 AND CSCU<=CSMOI
		AND DocSo_PHT.dbo.DS2012.KY ='05'
		
-- UPDATE LO TRINH
UPDATE KHACHHANG SET  MALOTRINH=t2.LOTRINH ,MALOTRINH2=t2.LOTRINH
FROM CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG as t2
WHERE KHACHHANG.DANHBA = t2.DANHBO
  AND LEFT(t2.LOTRINH,2) IN ('01','02','03','04','05','06','07','08','09','10')
 
-- UPDATE MAY DOC SO
UPDATE KHACHHANG SET DOT=17 where DANHBA='13202745339'
 = SUBSTRING(MALOTRINH,3,2) 

select * from KHACHHANG where DANHBA='13202745339'


