
SELECT SUBSTRING(LOTRINH,1,2) as 'DOT',kh.LOTRINH, kh.DANHBO, kh.HOPDONG, kh.HOTEN, kh.SONHA, kh.TENDUONG,P.TENPHUONG, q.TENQUAN,kh.HIEUDH, kh.CODH,SOTHANDH , VITRIDHN,CONVERT(varchar(10),kh.NGAYTHAY,103) as NGAYGAN, YEAR(kh.NGAYTHAY) AS NAM,hd.CODE,hd.CSMOI,hd.NHANVIEN
FROM  TB_DULIEUKHACHHANG kh,  PHUONG p, QUAN q,HOADONTH07_2013 hd  
WHERE kh.DANHBO= hd.DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND YEAR(kh.NGAYTHAY)=2009
ORDER BY  NGAYGAN ASC

SELECT SUBSTRING(LOTRINH,1,2) as 'DOT',kh.LOTRINH, kh.DANHBO, kh.HOPDONG, kh.HOTEN, kh.SONHA, kh.TENDUONG,P.TENPHUONG, q.TENQUAN,kh.HIEUDH, kh.CODH,SOTHANDH , VITRIDHN,CONVERT(varchar(10),kh.NGAYTHAY,103) as NGAYGAN, YEAR(kh.NGAYTHAY) AS NAM,hd.CODE,hd.CSMOI,hd.NHANVIEN
FROM  TB_DULIEUKHACHHANG kh,  PHUONG p, QUAN q,HOADONTH07_2013 hd  
WHERE kh.DANHBO= hd.DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND YEAR(kh.NGAYTHAY)=2009
AND SUBSTRING(LOTRINH,3,2) IN ('01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')
ORDER BY  NGAYGAN ASC

SELECT SUBSTRING(LOTRINH,1,2) as 'DOT',kh.LOTRINH, kh.DANHBO, kh.HOPDONG, kh.HOTEN, kh.SONHA, kh.TENDUONG,P.TENPHUONG, q.TENQUAN,kh.HIEUDH, kh.CODH,SOTHANDH , VITRIDHN,CONVERT(varchar(10),kh.NGAYTHAY,103) as NGAYGAN, YEAR(kh.NGAYTHAY) AS NAM,hd.CODE,hd.CSMOI,hd.NHANVIEN
FROM  TB_DULIEUKHACHHANG kh,  PHUONG p, QUAN q,HOADONTH07_2013 hd  
WHERE kh.DANHBO= hd.DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND YEAR(kh.NGAYTHAY)=2009
AND SUBSTRING(LOTRINH,3,2) IN ('16','17','18','19','20','21','22','23','24','25','26','27','28','29','30')
ORDER BY  NGAYGAN ASC

SELECT SUBSTRING(LOTRINH,1,2) as 'DOT',kh.LOTRINH, kh.DANHBO, kh.HOPDONG, kh.HOTEN, kh.SONHA, kh.TENDUONG,P.TENPHUONG, q.TENQUAN,kh.HIEUDH, kh.CODH,SOTHANDH , VITRIDHN,CONVERT(varchar(10),kh.NGAYTHAY,103) as NGAYGAN, YEAR(kh.NGAYTHAY) AS NAM,hd.CODE,hd.CSMOI,hd.NHANVIEN
FROM  TB_DULIEUKHACHHANG kh,  PHUONG p, QUAN q,HOADONTH07_2013 hd  
WHERE kh.DANHBO= hd.DANHBO AND kh.QUAN = q.MAQUAN AND q.MAQUAN=p.MAQUAN AND kh.PHUONG=p.MAPHUONG AND YEAR(kh.NGAYTHAY)=2009
AND SUBSTRING(LOTRINH,3,2) IN ('31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46')
ORDER BY  NGAYGAN ASC
