--- To Thay Dong Ho Nuoc
DROP VIEW V_DHN_BANGKE
GO

CREATE VIEW V_DHN_BANGKE
AS
	SELECT loai.TENBANGKE,kh.HOPDONG,kh.HOTEN,kh.SONHA,kh.TENDUONG,thay.*
	FROM TB_THAYDHN thay, TB_LOAIBANGKE loai,TB_DULIEUKHACHHANG kh
	WHERE thay.DHN_DANHBO=kh.DANHBO AND thay.DHN_LOAIBANGKE=loai.LOAIBK
GO

DROP VIEW V_TCTB_TKVATTUTHAY
GO

CREATE VIEW V_TCTB_TKVATTUTHAY
AS
	SELECT STT,MAVT,TENVT,DVT,SUM(SOLUONG) AS 'TONGSL'
	FROM TB_VATUTHAY_DHN 
	GROUP BY  STT,MAVT,TENVT,DVT
GO


DROP VIEW V_TCTB_HOANCONGNHANH
GO

CREATE VIEW V_TCTB_HOANCONGNHANH
AS 
	SELECT HCT_NGAYGAN,DHN_NGAYBAOTHAY,(DHN_TODS+'-'+CONVERT(VARCHAR(20),DHN_SOBANGKE)) AS 'TENBK'
	,count(case when HCT_TRONGAI ='0' then 1 else null end) AS 'HOANTAT'  
	,count(case when HCT_TRONGAI ='1' then 1 else null end) AS 'TRONGAI'  
	FROM TB_THAYDHN 
	GROUP BY (DHN_TODS+'-'+CONVERT(VARCHAR(20),DHN_SOBANGKE)),HCT_NGAYGAN,DHN_NGAYBAOTHAY
GO

select *, N'Ngô Gia An' as 'NGUOIDUYET' FROM V_TCTB_HOANCONGNHANH  ORDER BY TENBK ASC 