<?xml version="1.0" encoding="utf-8"?><Database Name="CallCenter" Class="dbCallCenterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HP_G7\KD;Initial Catalog=CallCenter;Persist Security Info=True;User ID=sa" SettingsObjectName="CAPNUOCTANHOA.Properties.Settings" SettingsPropertyName="CallCenterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KT_BaoBe" Member="KT_BaoBes">
    <Type Name="KT_BaoBe">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Lng" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoaiBao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTiepNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayThucHien" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoaiThucHien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KetQua" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Img" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FilePdf" Type="System.Data.Linq.Binary" DbType="VarBinary(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[To]" Member="Tos">
    <Type Name="To">
      <Column Name="MaTo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="To_NguoiDung" Member="NguoiDungs" ThisKey="MaTo" OtherKey="MaTo" Type="NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.KT_DongNuoc" Member="KT_DongNuocs">
    <Type Name="KT_DongNuoc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DongMo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="lat" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="lng" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TuGio" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DenGio" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KT_Van" Member="KT_Vans">
    <Type Name="KT_Van">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="STT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TuyenOng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CoVan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChanTuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XaCan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TCH" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TLKCoLon" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VanBien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LoaiVan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChieuDong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoVong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoSau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongTinMang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTiepNhan" Member="LoaiTiepNhans">
    <Type Name="LoaiTiepNhan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menu" Member="Menus">
    <Type Name="Menu">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMenu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMenuCha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenuCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs" ThisKey="MaMenu" OtherKey="MaMenu" Type="PhanQuyenNguoiDung" />
      <Association Name="Menu_PhanQuyenNhom" Member="PhanQuyenNhoms" ThisKey="MaMenu" OtherKey="MaMenu" Type="PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NamVaoLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayPhepNamCu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayPhepNamMoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongNgayPhep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoGiamDoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Doi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ToTruong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HanhThu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DongNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VanPhong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChamCong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="An" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NguoiDung_PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs" ThisKey="MaND" OtherKey="MaND" Type="PhanQuyenNguoiDung" />
      <Association Name="To_NguoiDung" Member="To" ThisKey="MaTo" OtherKey="MaTo" Type="To" IsForeignKey="true" />
      <Association Name="Nhom_NguoiDung" Member="Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nhom" Member="Nhoms">
    <Type Name="Nhom">
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Nhom_NguoiDung" Member="NguoiDungs" ThisKey="MaNhom" OtherKey="MaNhom" Type="NguoiDung" />
      <Association Name="Nhom_PhanQuyenNhom" Member="PhanQuyenNhoms" ThisKey="MaNhom" OtherKey="MaNhom" Type="PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyenNguoiDung" Member="PhanQuyenNguoiDungs">
    <Type Name="PhanQuyenNguoiDung">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNguoiDung" Member="Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="Menu" IsForeignKey="true" />
      <Association Name="NguoiDung_PhanQuyenNguoiDung" Member="NguoiDung" ThisKey="MaND" OtherKey="MaND" Type="NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanQuyenNhom" Member="PhanQuyenNhoms">
    <Type Name="PhanQuyenNhom">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menu_PhanQuyenNhom" Member="Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="Menu" IsForeignKey="true" />
      <Association Name="Nhom_PhanQuyenNhom" Member="Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhongBan" Member="PhongBans">
    <Type Name="PhongBan">
      <Column Name="MaPhong" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TiepNhan" Member="TiepNhans">
    <Type Name="TiepNhan">
      <Column Name="LoaiTN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoHoSo" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="SoNha" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TenDuong" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiHs" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChuyenHS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonViChuyen" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="NgayChuyen" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayXuLy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KetQuaXuLy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NhanVienXuLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>