<?xml version="1.0" encoding="utf-8"?><Database Name="DocSoTH" Class="DocSoTHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HP_G7\KD;Initial Catalog=DocSoTH;Persist Security Info=True;User ID=sa" SettingsObjectName="CAPNUOCTANHOA.Properties.Settings" SettingsPropertyName="DocSoTHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BaoThay" Member="BaoThays">
    <Type Name="BaoThay">
      <Column Name="BaoThayID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DanhBa" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoaiBT" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NgayThay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HieuMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CoMoi" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SoThanMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ViTriMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiThanMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiCoMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CSGo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CSGan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>