<?xml version="1.0" encoding="utf-8"?><Database Name="TANHOAGIS" Class="GISDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVERG8-01\SERVER2008;Initial Catalog=TANHOAGIS;Persist Security Info=True;User ID=sa" SettingsObjectName="CAPNUOCTANHOA.Properties.Settings" SettingsPropertyName="TANHOAGISConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HOSO_DONGHOKHACHHANG" Member="HOSO_DONGHOKHACHHANGs">
    <Type Name="HOSO_DONGHOKHACHHANG">
      <Column Name="OBJECTID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DBDongHoNuoc" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="MaHoSo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DataBlob" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="NguoiCapNhat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiFile" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="TenHoSo" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>