#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPNUOCTANHOA.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KTKS_DonKH")]
	public partial class KTKSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCTBamChi(CTBamChi instance);
    partial void UpdateCTBamChi(CTBamChi instance);
    partial void DeleteCTBamChi(CTBamChi instance);
    partial void InsertTTKH_LoaiTiepNhan(TTKH_LoaiTiepNhan instance);
    partial void UpdateTTKH_LoaiTiepNhan(TTKH_LoaiTiepNhan instance);
    partial void DeleteTTKH_LoaiTiepNhan(TTKH_LoaiTiepNhan instance);
    partial void InsertTTKH_TiepNhan(TTKH_TiepNhan instance);
    partial void UpdateTTKH_TiepNhan(TTKH_TiepNhan instance);
    partial void DeleteTTKH_TiepNhan(TTKH_TiepNhan instance);
    #endregion
		
		public KTKSDataContext() : 
				base(global::CAPNUOCTANHOA.Properties.Settings.Default.KTKS_DonKHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KTKSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KTKSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KTKSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KTKSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CTBamChi> CTBamChis
		{
			get
			{
				return this.GetTable<CTBamChi>();
			}
		}
		
		public System.Data.Linq.Table<TTKH_LoaiTiepNhan> TTKH_LoaiTiepNhans
		{
			get
			{
				return this.GetTable<TTKH_LoaiTiepNhan>();
			}
		}
		
		public System.Data.Linq.Table<TTKH_TiepNhan> TTKH_TiepNhans
		{
			get
			{
				return this.GetTable<TTKH_TiepNhan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTBamChi")]
	public partial class CTBamChi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _MaCTBC;
		
		private string _DanhBo;
		
		private string _HopDong;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private System.Nullable<int> _GiaBieu;
		
		private System.Nullable<int> _DinhMuc;
		
		private string _Dot;
		
		private string _Ky;
		
		private string _Nam;
		
		private System.Nullable<System.DateTime> _NgayBC;
		
		private string _HienTrangKiemTra;
		
		private string _Hieu;
		
		private System.Nullable<int> _Co;
		
		private string _SoThan;
		
		private System.Nullable<int> _ChiSo;
		
		private string _TinhTrangChiSo;
		
		private string _ChiMatSo;
		
		private string _ChiKhoaGoc;
		
		private string _MucDichSuDung;
		
		private System.Nullable<int> _VienChi;
		
		private System.Nullable<double> _DayChi;
		
		private string _TrangThaiBC;
		
		private string _GhiChu;
		
		private string _MaSoBC;
		
		private string _TheoYeuCau;
		
		private System.Nullable<decimal> _MaBC;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTBCChanging(decimal value);
    partial void OnMaCTBCChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnHopDongChanging(string value);
    partial void OnHopDongChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnGiaBieuChanging(System.Nullable<int> value);
    partial void OnGiaBieuChanged();
    partial void OnDinhMucChanging(System.Nullable<int> value);
    partial void OnDinhMucChanged();
    partial void OnDotChanging(string value);
    partial void OnDotChanged();
    partial void OnKyChanging(string value);
    partial void OnKyChanged();
    partial void OnNamChanging(string value);
    partial void OnNamChanged();
    partial void OnNgayBCChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBCChanged();
    partial void OnHienTrangKiemTraChanging(string value);
    partial void OnHienTrangKiemTraChanged();
    partial void OnHieuChanging(string value);
    partial void OnHieuChanged();
    partial void OnCoChanging(System.Nullable<int> value);
    partial void OnCoChanged();
    partial void OnSoThanChanging(string value);
    partial void OnSoThanChanged();
    partial void OnChiSoChanging(System.Nullable<int> value);
    partial void OnChiSoChanged();
    partial void OnTinhTrangChiSoChanging(string value);
    partial void OnTinhTrangChiSoChanged();
    partial void OnChiMatSoChanging(string value);
    partial void OnChiMatSoChanged();
    partial void OnChiKhoaGocChanging(string value);
    partial void OnChiKhoaGocChanged();
    partial void OnMucDichSuDungChanging(string value);
    partial void OnMucDichSuDungChanged();
    partial void OnVienChiChanging(System.Nullable<int> value);
    partial void OnVienChiChanged();
    partial void OnDayChiChanging(System.Nullable<double> value);
    partial void OnDayChiChanged();
    partial void OnTrangThaiBCChanging(string value);
    partial void OnTrangThaiBCChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnMaSoBCChanging(string value);
    partial void OnMaSoBCChanged();
    partial void OnTheoYeuCauChanging(string value);
    partial void OnTheoYeuCauChanged();
    partial void OnMaBCChanging(System.Nullable<decimal> value);
    partial void OnMaBCChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(System.Nullable<int> value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(System.Nullable<int> value);
    partial void OnModifyByChanged();
    #endregion
		
		public CTBamChi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTBC", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal MaCTBC
		{
			get
			{
				return this._MaCTBC;
			}
			set
			{
				if ((this._MaCTBC != value))
				{
					this.OnMaCTBCChanging(value);
					this.SendPropertyChanging();
					this._MaCTBC = value;
					this.SendPropertyChanged("MaCTBC");
					this.OnMaCTBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="NVarChar(50)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HopDong", DbType="NVarChar(50)")]
		public string HopDong
		{
			get
			{
				return this._HopDong;
			}
			set
			{
				if ((this._HopDong != value))
				{
					this.OnHopDongChanging(value);
					this.SendPropertyChanging();
					this._HopDong = value;
					this.SendPropertyChanged("HopDong");
					this.OnHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBieu", DbType="Int")]
		public System.Nullable<int> GiaBieu
		{
			get
			{
				return this._GiaBieu;
			}
			set
			{
				if ((this._GiaBieu != value))
				{
					this.OnGiaBieuChanging(value);
					this.SendPropertyChanging();
					this._GiaBieu = value;
					this.SendPropertyChanged("GiaBieu");
					this.OnGiaBieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DinhMuc", DbType="Int")]
		public System.Nullable<int> DinhMuc
		{
			get
			{
				return this._DinhMuc;
			}
			set
			{
				if ((this._DinhMuc != value))
				{
					this.OnDinhMucChanging(value);
					this.SendPropertyChanging();
					this._DinhMuc = value;
					this.SendPropertyChanged("DinhMuc");
					this.OnDinhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dot", DbType="NVarChar(50)")]
		public string Dot
		{
			get
			{
				return this._Dot;
			}
			set
			{
				if ((this._Dot != value))
				{
					this.OnDotChanging(value);
					this.SendPropertyChanging();
					this._Dot = value;
					this.SendPropertyChanged("Dot");
					this.OnDotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ky", DbType="NVarChar(50)")]
		public string Ky
		{
			get
			{
				return this._Ky;
			}
			set
			{
				if ((this._Ky != value))
				{
					this.OnKyChanging(value);
					this.SendPropertyChanging();
					this._Ky = value;
					this.SendPropertyChanged("Ky");
					this.OnKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="NVarChar(50)")]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this.OnNamChanging(value);
					this.SendPropertyChanging();
					this._Nam = value;
					this.SendPropertyChanged("Nam");
					this.OnNamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBC
		{
			get
			{
				return this._NgayBC;
			}
			set
			{
				if ((this._NgayBC != value))
				{
					this.OnNgayBCChanging(value);
					this.SendPropertyChanging();
					this._NgayBC = value;
					this.SendPropertyChanged("NgayBC");
					this.OnNgayBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HienTrangKiemTra", DbType="NVarChar(100)")]
		public string HienTrangKiemTra
		{
			get
			{
				return this._HienTrangKiemTra;
			}
			set
			{
				if ((this._HienTrangKiemTra != value))
				{
					this.OnHienTrangKiemTraChanging(value);
					this.SendPropertyChanging();
					this._HienTrangKiemTra = value;
					this.SendPropertyChanged("HienTrangKiemTra");
					this.OnHienTrangKiemTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hieu", DbType="NVarChar(50)")]
		public string Hieu
		{
			get
			{
				return this._Hieu;
			}
			set
			{
				if ((this._Hieu != value))
				{
					this.OnHieuChanging(value);
					this.SendPropertyChanging();
					this._Hieu = value;
					this.SendPropertyChanged("Hieu");
					this.OnHieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Co", DbType="Int")]
		public System.Nullable<int> Co
		{
			get
			{
				return this._Co;
			}
			set
			{
				if ((this._Co != value))
				{
					this.OnCoChanging(value);
					this.SendPropertyChanging();
					this._Co = value;
					this.SendPropertyChanged("Co");
					this.OnCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThan", DbType="NVarChar(50)")]
		public string SoThan
		{
			get
			{
				return this._SoThan;
			}
			set
			{
				if ((this._SoThan != value))
				{
					this.OnSoThanChanging(value);
					this.SendPropertyChanging();
					this._SoThan = value;
					this.SendPropertyChanged("SoThan");
					this.OnSoThanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiSo", DbType="Int")]
		public System.Nullable<int> ChiSo
		{
			get
			{
				return this._ChiSo;
			}
			set
			{
				if ((this._ChiSo != value))
				{
					this.OnChiSoChanging(value);
					this.SendPropertyChanging();
					this._ChiSo = value;
					this.SendPropertyChanged("ChiSo");
					this.OnChiSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangChiSo", DbType="NVarChar(50)")]
		public string TinhTrangChiSo
		{
			get
			{
				return this._TinhTrangChiSo;
			}
			set
			{
				if ((this._TinhTrangChiSo != value))
				{
					this.OnTinhTrangChiSoChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangChiSo = value;
					this.SendPropertyChanged("TinhTrangChiSo");
					this.OnTinhTrangChiSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiMatSo", DbType="NVarChar(50)")]
		public string ChiMatSo
		{
			get
			{
				return this._ChiMatSo;
			}
			set
			{
				if ((this._ChiMatSo != value))
				{
					this.OnChiMatSoChanging(value);
					this.SendPropertyChanging();
					this._ChiMatSo = value;
					this.SendPropertyChanged("ChiMatSo");
					this.OnChiMatSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiKhoaGoc", DbType="NVarChar(50)")]
		public string ChiKhoaGoc
		{
			get
			{
				return this._ChiKhoaGoc;
			}
			set
			{
				if ((this._ChiKhoaGoc != value))
				{
					this.OnChiKhoaGocChanging(value);
					this.SendPropertyChanging();
					this._ChiKhoaGoc = value;
					this.SendPropertyChanged("ChiKhoaGoc");
					this.OnChiKhoaGocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucDichSuDung", DbType="NVarChar(200)")]
		public string MucDichSuDung
		{
			get
			{
				return this._MucDichSuDung;
			}
			set
			{
				if ((this._MucDichSuDung != value))
				{
					this.OnMucDichSuDungChanging(value);
					this.SendPropertyChanging();
					this._MucDichSuDung = value;
					this.SendPropertyChanged("MucDichSuDung");
					this.OnMucDichSuDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VienChi", DbType="Int")]
		public System.Nullable<int> VienChi
		{
			get
			{
				return this._VienChi;
			}
			set
			{
				if ((this._VienChi != value))
				{
					this.OnVienChiChanging(value);
					this.SendPropertyChanging();
					this._VienChi = value;
					this.SendPropertyChanged("VienChi");
					this.OnVienChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DayChi", DbType="Float")]
		public System.Nullable<double> DayChi
		{
			get
			{
				return this._DayChi;
			}
			set
			{
				if ((this._DayChi != value))
				{
					this.OnDayChiChanging(value);
					this.SendPropertyChanging();
					this._DayChi = value;
					this.SendPropertyChanged("DayChi");
					this.OnDayChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiBC", DbType="NVarChar(100)")]
		public string TrangThaiBC
		{
			get
			{
				return this._TrangThaiBC;
			}
			set
			{
				if ((this._TrangThaiBC != value))
				{
					this.OnTrangThaiBCChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiBC = value;
					this.SendPropertyChanged("TrangThaiBC");
					this.OnTrangThaiBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoBC", DbType="NVarChar(50)")]
		public string MaSoBC
		{
			get
			{
				return this._MaSoBC;
			}
			set
			{
				if ((this._MaSoBC != value))
				{
					this.OnMaSoBCChanging(value);
					this.SendPropertyChanging();
					this._MaSoBC = value;
					this.SendPropertyChanged("MaSoBC");
					this.OnMaSoBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheoYeuCau", DbType="NVarChar(MAX)")]
		public string TheoYeuCau
		{
			get
			{
				return this._TheoYeuCau;
			}
			set
			{
				if ((this._TheoYeuCau != value))
				{
					this.OnTheoYeuCauChanging(value);
					this.SendPropertyChanging();
					this._TheoYeuCau = value;
					this.SendPropertyChanged("TheoYeuCau");
					this.OnTheoYeuCauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBC", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaBC
		{
			get
			{
				return this._MaBC;
			}
			set
			{
				if ((this._MaBC != value))
				{
					this.OnMaBCChanging(value);
					this.SendPropertyChanging();
					this._MaBC = value;
					this.SendPropertyChanged("MaBC");
					this.OnMaBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTKH_LoaiTiepNhan")]
	public partial class TTKH_LoaiTiepNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoai;
		
		private string _LoaiKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnLoaiKHChanging(string value);
    partial void OnLoaiKHChanged();
    #endregion
		
		public TTKH_LoaiTiepNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(MAX)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKH", DbType="VarChar(50)")]
		public string LoaiKH
		{
			get
			{
				return this._LoaiKH;
			}
			set
			{
				if ((this._LoaiKH != value))
				{
					this.OnLoaiKHChanging(value);
					this.SendPropertyChanging();
					this._LoaiKH = value;
					this.SendPropertyChanged("LoaiKH");
					this.OnLoaiKHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTKH_TiepNhan")]
	public partial class TTKH_TiepNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LoaiTN;
		
		private string _SoHoSo;
		
		private string _DanhBo;
		
		private string _DienThoai;
		
		private string _TenKH;
		
		private string _SoNha;
		
		private string _TenDuong;
		
		private string _Phuong;
		
		private string _Quan;
		
		private string _LoaiHs;
		
		private System.Nullable<System.DateTime> _NgayNhan;
		
		private string _GhiChu;
		
		private System.Nullable<bool> _ChuyenHS;
		
		private System.Nullable<int> _MaDVChuyen;
		
		private string _DonViChuyen;
		
		private System.Nullable<System.DateTime> _NgayChuyen;
		
		private System.Nullable<System.DateTime> _NgayXuLy;
		
		private string _KetQuaXuLy;
		
		private string _NhanVienXuLy;
		
		private System.Nullable<bool> _Mess;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private string _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private string _ModifyBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoaiTNChanging(string value);
    partial void OnLoaiTNChanged();
    partial void OnSoHoSoChanging(string value);
    partial void OnSoHoSoChanged();
    partial void OnDanhBoChanging(string value);
    partial void OnDanhBoChanged();
    partial void OnDienThoaiChanging(string value);
    partial void OnDienThoaiChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoNhaChanging(string value);
    partial void OnSoNhaChanged();
    partial void OnTenDuongChanging(string value);
    partial void OnTenDuongChanged();
    partial void OnPhuongChanging(string value);
    partial void OnPhuongChanged();
    partial void OnQuanChanging(string value);
    partial void OnQuanChanged();
    partial void OnLoaiHsChanging(string value);
    partial void OnLoaiHsChanged();
    partial void OnNgayNhanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnChuyenHSChanging(System.Nullable<bool> value);
    partial void OnChuyenHSChanged();
    partial void OnMaDVChuyenChanging(System.Nullable<int> value);
    partial void OnMaDVChuyenChanged();
    partial void OnDonViChuyenChanging(string value);
    partial void OnDonViChuyenChanged();
    partial void OnNgayChuyenChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenChanged();
    partial void OnNgayXuLyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXuLyChanged();
    partial void OnKetQuaXuLyChanging(string value);
    partial void OnKetQuaXuLyChanged();
    partial void OnNhanVienXuLyChanging(string value);
    partial void OnNhanVienXuLyChanged();
    partial void OnMessChanging(System.Nullable<bool> value);
    partial void OnMessChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnCreateByChanging(string value);
    partial void OnCreateByChanged();
    partial void OnModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifyDateChanged();
    partial void OnModifyByChanging(string value);
    partial void OnModifyByChanged();
    #endregion
		
		public TTKH_TiepNhan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTN", DbType="VarChar(50)")]
		public string LoaiTN
		{
			get
			{
				return this._LoaiTN;
			}
			set
			{
				if ((this._LoaiTN != value))
				{
					this.OnLoaiTNChanging(value);
					this.SendPropertyChanging();
					this._LoaiTN = value;
					this.SendPropertyChanged("LoaiTN");
					this.OnLoaiTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoSo", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHoSo
		{
			get
			{
				return this._SoHoSo;
			}
			set
			{
				if ((this._SoHoSo != value))
				{
					this.OnSoHoSoChanging(value);
					this.SendPropertyChanging();
					this._SoHoSo = value;
					this.SendPropertyChanged("SoHoSo");
					this.OnSoHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="VarChar(50)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this.OnDanhBoChanging(value);
					this.SendPropertyChanging();
					this._DanhBo = value;
					this.SendPropertyChanged("DanhBo");
					this.OnDanhBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="VarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this.OnDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._DienThoai = value;
					this.SendPropertyChanged("DienThoai");
					this.OnDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(150)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNha", DbType="NVarChar(150)")]
		public string SoNha
		{
			get
			{
				return this._SoNha;
			}
			set
			{
				if ((this._SoNha != value))
				{
					this.OnSoNhaChanging(value);
					this.SendPropertyChanging();
					this._SoNha = value;
					this.SendPropertyChanged("SoNha");
					this.OnSoNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuong", DbType="NVarChar(150)")]
		public string TenDuong
		{
			get
			{
				return this._TenDuong;
			}
			set
			{
				if ((this._TenDuong != value))
				{
					this.OnTenDuongChanging(value);
					this.SendPropertyChanging();
					this._TenDuong = value;
					this.SendPropertyChanged("TenDuong");
					this.OnTenDuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this.OnPhuongChanging(value);
					this.SendPropertyChanging();
					this._Phuong = value;
					this.SendPropertyChanged("Phuong");
					this.OnPhuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this.OnQuanChanging(value);
					this.SendPropertyChanging();
					this._Quan = value;
					this.SendPropertyChanged("Quan");
					this.OnQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHs", DbType="VarChar(50)")]
		public string LoaiHs
		{
			get
			{
				return this._LoaiHs;
			}
			set
			{
				if ((this._LoaiHs != value))
				{
					this.OnLoaiHsChanging(value);
					this.SendPropertyChanging();
					this._LoaiHs = value;
					this.SendPropertyChanged("LoaiHs");
					this.OnLoaiHsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhan
		{
			get
			{
				return this._NgayNhan;
			}
			set
			{
				if ((this._NgayNhan != value))
				{
					this.OnNgayNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayNhan = value;
					this.SendPropertyChanged("NgayNhan");
					this.OnNgayNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenHS", DbType="Bit")]
		public System.Nullable<bool> ChuyenHS
		{
			get
			{
				return this._ChuyenHS;
			}
			set
			{
				if ((this._ChuyenHS != value))
				{
					this.OnChuyenHSChanging(value);
					this.SendPropertyChanging();
					this._ChuyenHS = value;
					this.SendPropertyChanged("ChuyenHS");
					this.OnChuyenHSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDVChuyen", DbType="Int")]
		public System.Nullable<int> MaDVChuyen
		{
			get
			{
				return this._MaDVChuyen;
			}
			set
			{
				if ((this._MaDVChuyen != value))
				{
					this.OnMaDVChuyenChanging(value);
					this.SendPropertyChanging();
					this._MaDVChuyen = value;
					this.SendPropertyChanged("MaDVChuyen");
					this.OnMaDVChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViChuyen", DbType="NVarChar(50)")]
		public string DonViChuyen
		{
			get
			{
				return this._DonViChuyen;
			}
			set
			{
				if ((this._DonViChuyen != value))
				{
					this.OnDonViChuyenChanging(value);
					this.SendPropertyChanging();
					this._DonViChuyen = value;
					this.SendPropertyChanged("DonViChuyen");
					this.OnDonViChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyen", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayChuyen
		{
			get
			{
				return this._NgayChuyen;
			}
			set
			{
				if ((this._NgayChuyen != value))
				{
					this.OnNgayChuyenChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyen = value;
					this.SendPropertyChanged("NgayChuyen");
					this.OnNgayChuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXuLy", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayXuLy
		{
			get
			{
				return this._NgayXuLy;
			}
			set
			{
				if ((this._NgayXuLy != value))
				{
					this.OnNgayXuLyChanging(value);
					this.SendPropertyChanging();
					this._NgayXuLy = value;
					this.SendPropertyChanged("NgayXuLy");
					this.OnNgayXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KetQuaXuLy", DbType="NVarChar(250)")]
		public string KetQuaXuLy
		{
			get
			{
				return this._KetQuaXuLy;
			}
			set
			{
				if ((this._KetQuaXuLy != value))
				{
					this.OnKetQuaXuLyChanging(value);
					this.SendPropertyChanging();
					this._KetQuaXuLy = value;
					this.SendPropertyChanged("KetQuaXuLy");
					this.OnKetQuaXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienXuLy", DbType="NVarChar(50)")]
		public string NhanVienXuLy
		{
			get
			{
				return this._NhanVienXuLy;
			}
			set
			{
				if ((this._NhanVienXuLy != value))
				{
					this.OnNhanVienXuLyChanging(value);
					this.SendPropertyChanging();
					this._NhanVienXuLy = value;
					this.SendPropertyChanged("NhanVienXuLy");
					this.OnNhanVienXuLyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mess", DbType="Bit")]
		public System.Nullable<bool> Mess
		{
			get
			{
				return this._Mess;
			}
			set
			{
				if ((this._Mess != value))
				{
					this.OnMessChanging(value);
					this.SendPropertyChanging();
					this._Mess = value;
					this.SendPropertyChanged("Mess");
					this.OnMessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="NVarChar(50)")]
		public string CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this.OnCreateByChanging(value);
					this.SendPropertyChanging();
					this._CreateBy = value;
					this.SendPropertyChanged("CreateBy");
					this.OnCreateByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this.OnModifyDateChanging(value);
					this.SendPropertyChanging();
					this._ModifyDate = value;
					this.SendPropertyChanged("ModifyDate");
					this.OnModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="NVarChar(50)")]
		public string ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this.OnModifyByChanging(value);
					this.SendPropertyChanging();
					this._ModifyBy = value;
					this.SendPropertyChanged("ModifyBy");
					this.OnModifyByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
