UPDATE KHACHHANG
SET KHACHHANG.HIEU = LEFT(t2.HIEUDH,3), KHACHHANG.SOTHAN= t2.SOTHANDH  ,KHACHHANG.VITRI=t2.VITRIDHN
FROM KHACHHANG INNER JOIN  
 ( 
   SELECT DANHBO,HIEUDH,SOTHANDH, VITRIDHN
   FROM  CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG
   WHERE SOTHANDH IS NOT NULL
) as t2  
ON	KHACHHANG.DANHBA = t2.DANHBO

INSERT INTO BAOTHAYDHN (DANHBA, TENKH, SO, DUONG, HIEUMOI, COMOI, NGAYTHAY, CSGO, CSGAN, SOTHANMOI, VITRIMOI, MACHITHAN, MACHIGOC, LOAI)
SELECT DHN_DANHBO,HOTEN, SONHA,TENDUONG,LEFT(HCT_HIEUDHNGAN,3),HCT_CODHNGAN,HCT_NGAYGAN,HCT_CHISOGO,HCT_CHISOGAN,HCT_SOTHANGAN,VITRIDHN,HCT_CHITHAN,HCT_CHIGOC,(case when DHN_LOAIBANGKE='DK' then 1 else 2 end) AS LOAI
FROM CAPNUOCTANHOA.dbo.TB_THAYDHN thay,CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG kh
WHERE thay.DHN_DANHBO= kh.DANHBO AND HCT_TRONGAI='False'

758

SELECT COUNT(*)  FROM BAOTHAYDHN

SELECT DHN_DANHBO,HOTEN, SONHA,TENDUONG,HCT_HIEUDHNGAN,HCT_CODHNGAN,HCT_NGAYGAN,HCT_CHISOGO,HCT_CHISOGAN,HCT_SOTHANGAN,VITRIDHN,HCT_CHITHAN,HCT_CHIGOC,(case when DHN_LOAIBANGKE='DK' then 1 else 2 end) AS LOAI
FROM CAPNUOCTANHOA.dbo.TB_THAYDHN thay,CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG kh
WHERE thay.DHN_DANHBO= kh.DANHBO AND HCT_TRONGAI='False'
