<?xml version="1.0" encoding="utf-8"?><Database Name="CAPNUOCTANHOA" Class="CapNuocTanHoaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=CAPNUOCTANHOA;Persist Security Info=True;User ID=sa" SettingsObjectName="CAPNUOCTANHOA.Properties.Settings" SettingsPropertyName="CAPNUOCTANHOAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[HTDS-TODS]" Member="HTDS_TODs">
    <Type Name="HTDS_TOD">
      <Column Name="DANHBO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_VATUTHAY_DHN" Member="TB_VATUTHAY_DHNs">
    <Type Name="TB_VATUTHAY_DHN">
      <Column Name="ID_BC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_BAOTHAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOTTHAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAVT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TENVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TB_THAYDHN_TB_VATUTHAY_DHN" Member="TB_THAYDHN" ThisKey="ID_BAOTHAY" OtherKey="ID_BAOTHAY" Type="TB_THAYDHN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_PHONGBANDOI" Member="SYS_PHONGBANDOIs">
    <Type Name="SYS_PHONGBANDOI">
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="SYS_PHONGBANDOI_SYS_USER" Member="SYS_USERs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="SYS_USER" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_ROLES" Member="SYS_ROLEs">
    <Type Name="SYS_ROLE">
      <Column Name="ROLEID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROLENAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="SYS_ROLE_SYS_USER" Member="SYS_USERs" ThisKey="ROLEID" OtherKey="ROLEID" Type="SYS_USER" />
    </Type>
  </Table>
  <Table Name="dbo.SYS_USERS" Member="SYS_USERs">
    <Type Name="SYS_USER">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROLEID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ENABLED" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TODS" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="GIOIHAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DUYET" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SYS_PHONGBANDOI_SYS_USER" Member="SYS_PHONGBANDOI" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="SYS_PHONGBANDOI" IsForeignKey="true" />
      <Association Name="SYS_ROLE_SYS_USER" Member="SYS_ROLE" ThisKey="ROLEID" OtherKey="ROLEID" Type="SYS_ROLE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_DHN_BAOCAO" Member="TB_DHN_BAOCAOs">
    <Type Name="TB_DHN_BAOCAO">
      <Column Name="ID_BC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CVPGKD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENPGKD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CVDQLDH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENQLDHN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CVPGDKT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENPGDKT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CVKIEMTRA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENKIEMTRA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CVTHICONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENTHICONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_DULIEUKHACHHANG" Member="TB_DULIEUKHACHHANGs">
    <Type Name="TB_DULIEUKHACHHANG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KHU" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DOT" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CUON_GCS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CUON_STT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DANHBO" Type="System.String" DbType="VarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYGANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HOPDONG" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SONHA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENDUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHUONG" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QUAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHUKY" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODEFU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GIABIEU" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DINHMUC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CODH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HIEUDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOTHANDH" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CAP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHITHAN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHIGOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VITRIDHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SODHN" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NGAYTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MSTHUE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SOHO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CHISOKYTRUOC" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BAOTHAY" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_HIEUDONGHO" Member="TB_HIEUDONGHOs">
    <Type Name="TB_HIEUDONGHO">
      <Column Name="HIEUDH" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDONGHO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_LOAIBANGKE" Member="TB_LOAIBANGKEs">
    <Type Name="TB_LOAIBANGKE">
      <Column Name="LOAIBK" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBANGKE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TB_THAYDHN" Member="TB_THAYDHNs">
    <Type Name="TB_THAYDHN">
      <Column Name="ID_BAOTHAY" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DHN_LANTHAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LOAIBANGKE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_SOBANGKE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_DANHBO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DHN_NGAYBAOTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_DOT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DHN_TODS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CHITHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CHIGOC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_HIEUDHN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CODH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CAP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DHN_SOTHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CHISO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LYDOTHAY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_GHICHU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_NGAYCHUYEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DHN_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_CHISOGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_SOTHANGO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_HIEUDHNGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CODHNGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CAP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_SOTHANGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CHISOGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_LOAIDHGAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CHITHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CHIGOC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_TRONGAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_LYDOTRONGAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="TB_THAYDHN_TB_VATUTHAY_DHN" Member="TB_VATUTHAY_DHNs" ThisKey="ID_BAOTHAY" OtherKey="ID_BAOTHAY" Type="TB_VATUTHAY_DHN" />
    </Type>
  </Table>
  <Table Name="dbo.TB_VATUTHAY" Member="TB_VATUTHAYs">
    <Type Name="TB_VATUTHAY">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAVT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TENVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_DHN_BANGKE" Member="V_DHN_BANGKEs">
    <Type Name="V_DHN_BANGKE">
      <Column Name="TENBANGKE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HOPDONG" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SONHA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENDUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ID_BAOTHAY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DHN_LANTHAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LOAIBANGKE" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_SOBANGKE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_DANHBO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DHN_NGAYBAOTHAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_DOT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DHN_TODS" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CHITHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CHIGOC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_HIEUDHN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CODH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CAP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DHN_SOTHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_CHISO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DHN_LYDOTHAY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_GHICHU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DHN_NGAYCHUYEN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DHN_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DHN_MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_CHISOGO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_SOTHANGO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_HIEUDHNGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CODHNGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CAP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_SOTHANGAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CHISOGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HCT_LOAIDHGAN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_NGAYGAN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CHITHAN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CHIGOC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_TRONGAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HCT_LYDOTRONGAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HCT_CREATEDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_CREATEBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HCT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HCT_MODIFYBY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.V_TCTB_TKVATTUTHAY" Member="V_TCTB_TKVATTUTHAYs">
    <Type Name="V_TCTB_TKVATTUTHAY">
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAVT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TENVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TONGSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>