SELECT *,DOANHTHU1-DOANHTHU AS DOANHTHU2,
DT_KY1- ISNULL(DT_KY,0) AS DT_KY2,
DT_4KY1-ISNULL(DT_4KY,0) AS DT_4KY2, 
SANLUONG1-ISNULL(SANLUONG,0) AS SANLUONG2,
SLDHN1-ISNULL(SLDHN,0) AS SLDHN2,
TANGDHN1-ISNULL(TANGDHN,0) AS TANGDHN2,
DHN_NHO31-ISNULL(DHN_NHO3,0) AS DHN_NHO32,
GIABQ1-ISNULL(GIABQ,0) AS GIABQ2,
TONG_DM1-ISNULL(TONG_DM,0) AS TONG_DM2,
HDTB_PN1-ISNULL(HDTB_PN,0) AS HDTB_PN2,
HDTB_TB1-ISNULL(HDTB_TB,0) AS HDTB_TB2,
HDTB_TP1-ISNULL(HDTB_TP,0) AS HDTB_TP2,
HDTB1-ISNULL(HDTB,0) AS HDTB2,
HDTB_TANG1-ISNULL(HDTB_TANG,0) AS HDTB_TANG2,
HOADON01-ISNULL(HOADON0,0) AS HOADON02,
HOADON0_PN1-ISNULL(HOADON0_PN,0) AS HOADON0_PN2,
HOADON0_TB1-ISNULL(HOADON0_TB,0) AS HOADON0_TB2,
HOADON0_TP1-ISNULL(HOADON0_TP,0) AS HOADON0_TP2,
HOADON0_TG1-ISNULL(HOADON0_TG,0) AS HOADON0_TG2,
HOADON41-ISNULL(HOADON4,0) AS HOADON42,
HOADON4_PN1-ISNULL(HOADON4_PN,0) AS HOADON4_PN2,
HOADON4_TB1-ISNULL(HOADON4_TB,0) AS HOADON4_TB2,
HOADON4_TP1-ISNULL(HOADON4_TP,0) AS HOADON4_TP2,
HOADON4_TG1-ISNULL(HOADON4_TG,0) AS HOADON4_TG2,
HDTON_TRUOC1-ISNULL(HDTON_TRUOC,0) AS HDTON_TRUOC,
HDTON_TONG1-ISNULL(HDTON_TONG,0) AS HDTON_TONG2,
HDTON_TG1-ISNULL(HDTON_TG,0) AS HDTON_TG2,
HDTON_CQ1-ISNULL(HDTON_CQ,0) AS HDTON_CQ2,
SLTON_TONG1-ISNULL(SLTON_TONG,0) AS SLTON_TONG2,
SLTON_TG1-ISNULL(SLTON_TG,0) AS SLTON_TG2,
SLTON_CQ1-ISNULL(SLTON_TG,0) AS SLTON_TG2
FROM (
	SELECT KY,NAM, DOANHTHU, DT_KY, DT_4KY, SANLUONG, SLDHN, TANGDHN, 
	DHN_NHO3, GIABQ, TONG_DM, HDTB_PN, HDTB_TB, HDTB_TP, HDTB, 
	HDTB_TANG, HOADON0, HOADON0_PN, HOADON0_TB, HOADON0_TP, 
	HOADON0_TG, HOADON4, HOADON4_PN, HOADON4_TB, HOADON4_TP, 
	HOADON4_TG, HDTON_TRUOC, HDTON_TONG, HDTON_TG, HDTON_CQ, 
	SLTON_TONG, SLTON_TG, SLTON_CQ 
	FROM BAOCAO_KINHDOANH WHERE NAM=2011) AS T1
FULL OUTER JOIN (
	SELECT KY AS KY1 ,NAM AS NAM1,DOANHTHU AS DOANHTHU1,DT_KY AS DT_KY1,DT_4KY AS DT_4KY1,SANLUONG AS SANLUONG1,SLDHN AS SLDHN1,
	TANGDHN AS TANGDHN1,DHN_NHO3 AS DHN_NHO31,GIABQ AS GIABQ1,TONG_DM AS TONG_DM1,HDTB_PN AS HDTB_PN1,
	HDTB_TB AS HDTB_TB1,HDTB_TP AS HDTB_TP1,HDTB AS HDTB1,HDTB_TANG AS HDTB_TANG1,HOADON0 AS HOADON01,
	HOADON0_PN AS HOADON0_PN1,HOADON0_TB AS HOADON0_TB1,HOADON0_TP AS HOADON0_TP1,HOADON0_TG AS HOADON0_TG1,
	HOADON4 AS HOADON41,HOADON4_PN AS HOADON4_PN1,HOADON4_TB AS HOADON4_TB1,HOADON4_TP AS HOADON4_TP1,
	HOADON4_TG AS HOADON4_TG1,HDTON_TRUOC AS HDTON_TRUOC1,HDTON_TONG AS HDTON_TONG1,HDTON_TG AS HDTON_TG1,
	HDTON_CQ AS HDTON_CQ1,SLTON_TONG AS SLTON_TONG1,SLTON_TG AS SLTON_TG1,SLTON_CQ AS SLTON_CQ1 FROM BAOCAO_KINHDOANH WHERE NAM=2012
) AS T2
ON T1.KY=T2.KY1


--------------------------------------------
SELECT TB01.DOT_KT,TB01.SOLUONG_KT,TB01.TIEUTHU_KT,
	 TB02.DOT_THOKT,TB01.TIEUTHU_KT-TB02.TT_THOKT AS SS_THOKT,
	 TB01.SOLUONG_KN,TB01.TIEUTHU_KN,
	 TB02.TT_THOKN,TB01.TIEUTHU_KN-TB02.TT_THOKN AS SS_THOKN,
	 TB01.SOLUONG_KN-TB01.SOLUONG_KT AS DHN_TANG,
	 TB01.TIEUTHU_KN-TB01.TIEUTHU_KT AS TT_TANG
FROM 
	(SELECT T2.*,T1.SOLUONG_KN,T1.TIEUTHU_KN,SOLUONG_KN- SOLUONG_KT AS SS_SL,
	TIEUTHU_KN-TIEUTHU_KT AS SS_TT
	FROM (
	SELECT hd.DOT as DOT_KT, COUNT(hd.DANHBA) as SOLUONG_KT, SUM(hd.TIEUTHUBU) as TIEUTHU_KT
		FROM HOADON hd WHERE hd.NAM=2012 AND hd.KY=7 
		GROUP BY hd.DOT) AS T2
	FULL OUTER JOIN (
		SELECT hd.DOT as DOT_KN, COUNT(hd.DANHBA) as SOLUONG_KN, SUM(hd.TIEUTHUBU) as TIEUTHU_KN
		FROM HOADON hd WHERE hd.NAM=2012 AND hd.KY=8 
		GROUP BY hd.DOT) AS T1
	ON T1.DOT_KN=T2.DOT_KT
	) AS TB01
FULL OUTER JOIN(
	SELECT T3.*,T4.*
		FROM (
				SELECT ds.DOT AS DOT_THOKT, SUM(ds.TIEUTHU) AS TT_THOKT
				FROM DocSo_PHT.dbo.DS2012 ds
				WHERE ds.KY=7
				GROUP BY DOT) AS T3
		FULL OUTER JOIN (
				SELECT ds.DOT AS DOT_THOKN, SUM(ds.TIEUTHU) AS TT_THOKN
				FROM DocSo_PHT.dbo.DS2012 ds
				WHERE ds.KY=8
				GROUP BY DOT) AS T4
		ON T3.DOT_THOKT=T4.DOT_THOKN ) AS TB02
ON TB01.DOT_KT=TB02.DOT_THOKT
ORDER BY DOT_KT ASC

SELECT ds.DOT, SUM(ds.TIEUTHU)
FROM DocSo_PHT.dbo.DS2012 ds
WHERE ds.KY=7
group by DOT
