SELECT * FROM SOLIEUHD

UPDATE SOLIEUHD SET T10 =hd.LNCC
FROM HOADONTH10_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T10)
SELECT h.DANHBO, h.LNCC as 'T10'
FROM HOADONTH10_2013 h
WHERE CODE='M';