DELETE FROM SOLIEUHD

SELECT * FROM SOLIEUHD

UPDATE SOLIEUHD SET T1 =hd.LNCC
FROM HOADONTH01_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T1)
SELECT h.DANHBO, h.LNCC as 'T1'
FROM HOADONTH01_2013 h
WHERE CODE='M';

-------
UPDATE SOLIEUHD SET T2 =hd.LNCC
FROM HOADONTH02_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T2)
SELECT h.DANHBO, h.LNCC as 'T2'
FROM HOADONTH02_2013 h
WHERE CODE='M';
-----------
UPDATE SOLIEUHD SET T3 =hd.LNCC
FROM HOADONTH03_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T3)
SELECT h.DANHBO, h.LNCC as 'T3'
FROM HOADONTH03_2013 h
WHERE CODE='M';
---------------

UPDATE SOLIEUHD SET T4 =hd.LNCC
FROM HOADONTH04_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T4)
SELECT h.DANHBO, h.LNCC as 'T4'
FROM HOADONTH04_2013 h
WHERE CODE='M';
---

UPDATE SOLIEUHD SET T5 =hd.LNCC
FROM HOADONTH05_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T5)
SELECT h.DANHBO, h.LNCC as 'T5'
FROM HOADONTH05_2013 h
WHERE CODE='M';
-------------
UPDATE SOLIEUHD SET T6 =hd.LNCC
FROM HOADONTH06_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T6)
SELECT h.DANHBO, h.LNCC as 'T6'
FROM HOADONTH06_2013 h
WHERE CODE='M';

-------------
UPDATE SOLIEUHD SET T7 =hd.LNCC
FROM HOADONTH07_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T7)
SELECT h.DANHBO, h.LNCC as 'T7'
FROM HOADONTH07_2013 h
WHERE CODE='M';
-------------
UPDATE SOLIEUHD SET T8 =hd.LNCC
FROM HOADONTH08_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T8)
SELECT h.DANHBO, h.LNCC as 'T8'
FROM HOADONTH08_2013 h
WHERE CODE='M';
-------------
UPDATE SOLIEUHD SET T9 =hd.LNCC
FROM HOADONTH09_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T9)
SELECT h.DANHBO, h.LNCC as 'T9'
FROM HOADONTH09_2013 h
WHERE CODE='M';
-------------
UPDATE SOLIEUHD SET T10 =hd.LNCC
FROM HOADONTH10_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T10)
SELECT h.DANHBO, h.LNCC as 'T10'
FROM HOADONTH10_2013 h
WHERE CODE='M';

-------------
UPDATE SOLIEUHD SET T11 =hd.LNCC
FROM HOADONTH11_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T11)
SELECT h.DANHBO, h.LNCC as 'T11'
FROM HOADONTH11_2013 h
WHERE CODE='M';
-------------
UPDATE SOLIEUHD SET T12 =hd.LNCC
FROM HOADONTH12_2013 hd
WHERE SOLIEUHD.DANHBO= hd.DANHBO


INSERT INTO SOLIEUHD(DANHBO,T12)
SELECT h.DANHBO, h.LNCC as 'T12'
FROM HOADONTH12_2013 h
WHERE CODE='M';

